#!/bin/bash

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "------------------------------------------------"
echo "   🔥 INCENDO COMMAND CENTER - LAN INSTALLER 🔥   "
echo "------------------------------------------------"
echo -e "${NC}"

# 1. Check for Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Error: Docker is not installed.${NC}"
    echo "Please install Docker Desktop or Docker Engine before running this script."
    exit 1
fi

echo -e "${GREEN}✅ Docker is installed.${NC}"

# 2. Detect IP Address (Mac/Linux compatible)
DEFAULT_IP="localhost"
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    DETECTED_IP=$(ipconfig getifaddr en0)
else
    # Linux (Raspberry Pi/Ubuntu)
    DETECTED_IP=$(hostname -I | awk '{print $1}')
fi

if [ ! -z "$DETECTED_IP" ]; then
    DEFAULT_IP=$DETECTED_IP
fi

# 3. Prompt for IP
echo ""
echo "To make this dashboard accessible to other devices on your WiFi,"
echo "we need to know this machine's Local IP address."
echo ""
read -p "Enter Local IP [$DEFAULT_IP]: " USER_IP
USER_IP=${USER_IP:-$DEFAULT_IP}

echo ""
echo -e "📝 Configuring system for: ${CYAN}${USER_IP}${NC}"

# 4. Create/Overwrite .env
cat > .env <<EOF
# Incendo Dashboard Configuration
# Auto-generated by install.sh on $(date)

# This tells the frontend where to find the MQTT broker
VITE_MQTT_BROKER_URL=ws://${USER_IP}:1884
EOF

echo -e "${GREEN}✅ Configuration saved to .env${NC}"

# 5. Launch Docker Compose
echo ""
echo "🚀 Building and starting containers..."
echo "(This might take a minute on the first run)"
echo ""

docker-compose up -d --build

if [ $? -eq 0 ]; then
    echo ""
    echo "------------------------------------------------"
    echo -e "🎉 ${GREEN}INSTALLATION SUCCESSFUL!${NC} 🎉"
    echo "------------------------------------------------"
    echo -e "📱 Access the Dashboard at:   ${CYAN}http://${USER_IP}:5173${NC}"
    echo -e "📡 MQTT Broker running at:    ${CYAN}ws://${USER_IP}:1884${NC}"
    echo "------------------------------------------------"
else
    echo ""
    echo -e "${RED}❌ Installation failed.${NC} Check the docker errors above."
fi
