# Incendo Dashboard - Windows Installer

Write-Host "------------------------------------------------" -ForegroundColor Cyan
Write-Host "   🔥 INCENDO COMMAND CENTER - WINDOWS SETUP 🔥   " -ForegroundColor Cyan
Write-Host "------------------------------------------------" -ForegroundColor Cyan

# 1. Check for Docker
if (!(Get-Command "docker" -ErrorAction SilentlyContinue)) {
    Write-Host "❌ Error: Docker is not installed." -ForegroundColor Red
    Write-Host "Please install Docker Desktop for Windows."
    exit 1
}

Write-Host "✅ Docker is installed." -ForegroundColor Green

# 2. Detect IP (Best Guess)
try {
    $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notlike "*Loopback*" -and $_.InterfaceAlias -notlike "*vEthernet*" } | Select-Object -First 1).IPAddress
} catch {
    $ip = "localhost"
}

if ([string]::IsNullOrWhiteSpace($ip)) { $ip = "localhost" }

Write-Host ""
Write-Host "To make this dashboard accessible on your LAN,"
Write-Host "we need this machine's Local IP address."
Write-Host ""
$userIp = Read-Host "Enter Local IP [$ip]"
if ([string]::IsNullOrWhiteSpace($userIp)) { $userIp = $ip }

Write-Host ""
Write-Host "📝 Configuring system for: $userIp" -ForegroundColor Cyan

# 3. Write .env file
$envContent = @"
# Incendo Dashboard Configuration
# Auto-generated by install.ps1

VITE_MQTT_BROKER_URL=ws://${userIp}:1884
"@

Set-Content -Path ".env" -Value $envContent
Write-Host "✅ Configuration saved to .env" -ForegroundColor Green

# 4. Run Docker
Write-Host ""
Write-Host "🚀 Building and starting containers..."
docker-compose up -d --build

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "------------------------------------------------" -ForegroundColor Cyan
    Write-Host "🎉 INSTALLATION SUCCESSFUL! 🎉" -ForegroundColor Green
    Write-Host "------------------------------------------------" -ForegroundColor Cyan
    Write-Host "📱 Access Dashboard:   http://${userIp}:5173"
    Write-Host "📡 MQTT Broker:        ws://${userIp}:1884"
    Write-Host "------------------------------------------------" -ForegroundColor Cyan
    Write-Host "Press Enter to exit..."
    Read-Host
} else {
    Write-Host "❌ Installation failed." -ForegroundColor Red
}
