server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy whatt.io requests to bypass CORS in production
    location /api/whatt/ {
        # Rewrite plain /api/whatt/foo to /foo
        rewrite ^/api/whatt/(.*) /$1 break;
        
        proxy_pass https://whatt.io;
        proxy_ssl_server_name on;
        proxy_set_header Host whatt.io;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Optional: Basic caching
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }
}
